# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RaspberryPI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 605)
        self.btnCaptureImage = QtWidgets.QPushButton(Dialog)
        self.btnCaptureImage.setGeometry(QtCore.QRect(100, 540, 121, 41))
        self.btnCaptureImage.setObjectName("btnCaptureImage")
        self.btnKI = QtWidgets.QPushButton(Dialog)
        self.btnKI.setGeometry(QtCore.QRect(300, 540, 121, 41))
        self.btnKI.setObjectName("btnKI")
        self.btnQuit = QtWidgets.QPushButton(Dialog)
        self.btnQuit.setGeometry(QtCore.QRect(500, 540, 121, 41))
        self.btnQuit.setObjectName("btnQuit")
        self.lblLiveView = QtWidgets.QLabel(Dialog)
        self.lblLiveView.setGeometry(QtCore.QRect(50, 20, 640, 480))
        self.lblLiveView.setObjectName("lblLiveView")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 10, 660, 500))
        self.frame.setStyleSheet("border: 10px solid grey;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.btnCaptureImage.raise_()
        self.btnKI.raise_()
        self.btnQuit.raise_()
        self.lblLiveView.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCaptureImage.setText(_translate("Dialog", "Bild aufnehmen"))
        self.btnKI.setText(_translate("Dialog", "Wort erkennen"))
        self.btnQuit.setText(_translate("Dialog", "Beenden"))
        self.lblLiveView.setText(_translate("Dialog", "LiveView"))

